"""create student_class

Revision ID: e37268418f39
Revises: 63f2c4fc9d3a
Create Date: 2021-04-25 22:22:38.410172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37268418f39'
down_revision = '63f2c4fc9d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('classes_student_id_fkey', 'classes', type_='foreignkey')
    op.drop_column('classes', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('classes_student_id_fkey', 'classes', 'students', ['student_id'], ['id'])
    op.drop_table('student_class')
    # ### end Alembic commands ###
